### ISSUE TITLE
Without Nx and ts-lint would be cool

### ISSUE THREAD

**Issue by farukbigez** [DevUnderflow/nx-node-apollo-grahql-mongo#3]
Ts-lint is deprecated and with nx codebase seems more complex to use a simple project. Without Nx and ts-lint would be useful.

**Comment by smithg09** [comment]
Yeah totally agreed, Just made this project to learn Nx with Node GraphQL.

**Comment by smithg09** [comment]
Maybe we can start a project using only typeGraphQL and typegoose 
Would love to get you onboard and discuss more on this

**Comment by farukbigez** [comment]
I'd be honored to do that. Thanks!

**Comment by smithg09** [comment]
Cool!
I'll setup a base project this weekend then we can start accordingly
